### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by sg-**
Change image as per https://github.com/ARMmbed/target-frdm-k64f-gcc/issues/14

### CODE REVIEW

**Comment by 0xc0170** [comment]
Can we resize the pic? 

It looks big - [rendered](https://github.com/ARMmbed/target-frdm-k64f-gcc/blob/sg--patch-1/readme.md)

**Comment by sg-** [comment]
How is that? Anything different, let me know the width

**Comment by 0xc0170** [comment]
Looking better.  

Where do we show a picture for a platform with all pins, like it used to be on platform mbed page? That one I use often.

**Comment by sg-** [comment]
on the board page. http://www.mbed.com/en/development/hardware/boards/freescale/frdm_k64f/

**Comment by autopulated** [comment]
merged this – but the new image does seem to have excessively large borders on it – is there a version without those?

Not a big deal...

**Pull request merged**
