### PR TITLE
Add network stack configuration to the target

### PR DESCRIPTION
**Pull request by bremoran**
This will allow configuration-based switching of network stacks.

### CODE REVIEW

**Comment by bremoran** [comment]
cc @bogdanm @autopulated

**Comment by bogdanm** [comment]
What exactly is this needed for?

**Comment by bremoran** [comment]
Selection of the network stack should not be enforced by the target.  This allows using network modules without writing a new target.  e.g. if your application uses a radio module, you can add a config.json that turns off lwip and turns on mbed-mesh-api.

**Comment by bogdanm** [comment]
Sorry, I still don't get it. If `selection of the network stack should not be enforced by the target` (which I agree with), then why is this information about the network stack needed in the target?

**Comment by bogdanm** [comment]
Got it, thanks. +1.

**Comment by autopulated** [comment]
Looks good to me

**Comment by bremoran** [comment]
Can a module owner publish this please?

**Pull request merged**
